# [Server Configuration]

agent:
  usage: True
  formatting: True
  url: "http://localhost:8000"
  model_id: "Qwen/Qwen3-8B-AWQ"
  system_prompt_path: "./prompts/{mode}/agent/system.md"
  user_prompt_path: "./prompts/{mode}/agent/user.md"

generator:
  url: "http://localhost:8001"
  model_id: "XGenerationLab/XiYanSQL-QwenCoder-3B-2504"
  prompt_path: "./prompts/{mode}/sql_generation.md"
